# Quick Start Guide

## Supported CompuLab Machines

* `cl-som-imx8`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-zeus -m imx-5.4.24-2.1.0.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b rel_imx_5.4.24_2.1.0-dev https://github.com/compulab-yokneam/meta-bsp-imx8mq.git sources/meta-bsp-imx8mq


# Set a desire machine
* `cl-som-imx8`
[source,console]
COMPULAB_MACHINE=cl-som-imx8

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-imx/tree/README?h=zeus-5.4.24-2.1.0[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

## imx8mq
This example shows how to build an NXP supported image for the `${COMPULAB_MACHINE}`
[source,console]
MACHINE=${COMPULAB_MACHINE} source sources/meta-bsp-imx8mq/tools/setup-imx8mq-env -b build-xwayland
bitbake -k imx-image-full

## IMX Boot Target
The default boot target is `IMXBOOT_TARGETS = flash_evk` configured by https://github.com/compulab-yokneam/meta-bsp-imx8mq/blob/rel_imx_5.4.24_2.1.0-dev/conf/machine/cl-som-imx8.conf#L39[cl-som-imx8.conf].

In order to override the default boot target add `IMXBOOT_TARGETS = <target>` to the conf/local.conf.

Available boot targets:
|===
|HDMI|DP|Empty
|IMXBOOT_TARGETS = flash_evk
|IMXBOOT_TARGETS = flash_dp_evk
|IMXBOOT_TARGETS = flash_evk_no_hdmi
|===


## Device Trees and available features
* sbc-imx8.dtb -- U-Boot default
* sbc-imx8-bluetooth.dtb -- i8265 BT instead of usb2 hub
* sbc-imx8-lvds-dcss.dtb -- LVDS on dcss
* sbc-imx8-lvds-lcdif.dtb -- LVDS on lcdif
* sbc-imx8-dual.dtb -- LVDS on lcdif and HDMI on dcss

## Set `fdt_file` value
* U-Boot
[source,console]
setenv fdt_file sbc-imx8-bluetooth.dtb

NOTE: In `U-Boot` boot environment device is the bootloader boot device.

* Linux
[source,console]
fw_setenv fdt_file sbc-imx8-bluetooth.dtb

NOTE: In `Linux` boot environment device defined by the `/etc/fw_env.config` file.
