SRC_URI_append_cl-som-imx8 = " \
	file://0000-cl-som-imx8-Add-machine-support.patch \
	file://0001-cl-som-imx8-dts-Update-for-5.4.24.patch \
	file://0002-sn65dsi83-Fix-build-issue-for-5.4.24.patch \
	file://0003-cl-som-imx8-config-Update-defconfig.patch \
	file://0004-cl-som-imx8-dts-Enable-mipi-lvds-configurations.patch \
	file://0005-cl-som-imx8-dts-Merge-compulab-imx8mq.dtsi-into-cl-s.patch \
	file://0006-cl-som-imx8-defconfig-Update-defconfig.patch \
"
