#!/bin/bash -e

MACHINE=${MACHINE:-cl-som-imx8}
DISTRO=${DISTRO:-fsl-imx-xwayland}
EULA=1
T="../sources/meta-bsp-imx8mq/templates"

BD=$(cat <<< $@ | awk '$0=$NF')

if [[ -d ${BD} ]];then

echo "Back to the build environment ${BD}"
. setup-environment ${BD}

else

. imx-setup-release.sh $@

for _d in ${T}/*;do
	_file=$(basename ${_d})
	for _f in ${_d}/*;do
		cat ${_f} >> conf/${_file}
	done;
done
fi
