SRC_URI_append_cl-som-imx8 = " \
	file://0000-cl-som-imx8-Add-basic-support.patch \
	file://0001-cl-som-imx8-Update-env-tool-and-conf.patch \
	file://0002-eeprom-Update-field-and-layout.patch \
	file://0003-bi_dram-Skip-zero-size-banks.patch \
	file://0004-soc-Don-t-take-the-rom_pointer-into-account.patch \
	file://0005-mem-Test-only-the-first-bank.patch \
	file://0006-compulab-mx8mq-ddr-Add-0x01060008-support.patch \
	file://0007-cl-som-imx8-config-Enable-fastboot.patch \
	file://cl-som-imx8_defconfig \
"
